name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this to your deployment branch, if different
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Change this to your deployment branch, if different

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - name: Checkout GitHub repository content
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Ensure compatibility with your app

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
